knp_snappy:
    temporary_folder: "%kernel.cache_dir%/snappy"
    process_timeout: 60
    pdf:        
        enabled:    true        
        binary:     C:/wkhtmltopdf/bin/wkhtmltopdf
        options:    []            
    image:
        enabled:    true
        binary:     C:/wkhtmltopdf/bin/wkhtmltoimage        
        options:    []
