<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'encrypt_decrypt' shared autowired service.

include_once $this->targetDirs[3].'\\src\\GeneralBundle\\Services\\encryptDecrypt.php';

return $this->services['encrypt_decrypt'] = new \App\GeneralBundle\Services\encryptDecrypt(($this->services['kernel'] ?? $this->get('kernel', 1)), ($this->services['swiftmailer.mailer.default'] ?? $this->load('getSwiftmailer_Mailer_DefaultService.php')), ($this->services['twig'] ?? $this->getTwigService()), $this);
