<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'general_webservice' shared autowired service.

return $this->services['general_webservice'] = new \App\GeneralBundle\Services\GeneralWebService(($this->services['kernel'] ?? $this->get('kernel', 1)), ($this->services['session'] ?? $this->getSessionService()), $this);
